import MarketingShell from '@/components/layout/MarketingShell'

export const metadata = { title: 'Privacy Policy' }

export default function PrivacyPage() {
  return (
    <MarketingShell>
      <div className="max-w-3xl mx-auto px-6 py-20">
        <h1 className="font-display text-[36px] font-black text-pp-dark mb-2">Privacy Policy</h1>
        <p className="text-[13px] font-bold text-pp-gray mb-10">Last updated: January 1, 2025</p>
        {[
          ['Information We Collect', 'We collect information you provide directly (name, email, phone, payment info) and information generated by your use of our service (messages, projects, quotes, reviews).'],
          ['How We Use Your Information', 'We use your information to provide and improve our services, communicate with you, process payments, and prevent fraud. We do not sell your personal data to third parties.'],
          ['Information Sharing', 'We share information between homeowners and service professionals as necessary to facilitate their interaction. We share data with service providers (payment processors, hosting) who assist in our operations.'],
          ['Data Retention', 'We retain your account data as long as your account is active. You may request deletion of your account and associated data at any time.'],
          ['Security', 'We implement industry-standard security measures including encryption, access controls, and regular security audits to protect your personal information.'],
          ['Cookies', 'We use cookies and similar technologies to provide our services, remember your preferences, and analyze usage patterns.'],
          ['Contact Us', 'If you have questions about this Privacy Policy, contact us at privacy@propertypros.com.'],
        ].map(([title, body]) => (
          <div key={title} className="mb-8">
            <h2 className="text-[18px] font-black text-pp-dark mb-3">{title}</h2>
            <p className="text-[14px] text-pp-gray leading-relaxed font-semibold">{body}</p>
          </div>
        ))}
      </div>
    </MarketingShell>
  )
}
